export const CREATE_FOLLOW = 'CREATE_FOLLOW';
export const FETCH_FOLLOW = 'FETCH_FOLLOW';

export const FETCH_FOLLOWER_FRIENDS = 'FETCH_FOLLOWER_FRIENDS';

export const FETCH_FRIENDS = 'FETCH_FRIENDS';
export const EDIT_FRIEND = 'EDIT_FRIEND';
export const DELETE_FOLLOW = 'DELETE_FOLLOW';

export const FETCH_USER_FRIENDS = 'FETCH_USER_FRIENDS';
